---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-connection
data:
  url: "jdbc:postgresql://my-release-postgresql:5432/postgres"
  username: "postgres"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-music
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-music
  template:
    metadata:
      labels:
        app: spring-music
    spec:
      containers:
        - name: workload
          image: us-central1-docker.pkg.dev/meyerg/k8slab/spring-music:1.0-meyerg
          ports:
            - containerPort: 8080
          env:
            - name: spring_profiles_active
              value: blue
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-connection
                  key: url  
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-connection
                  key: username  
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-release-postgresql
                  key: postgres-password            

